name: Solar Frontend CI

on:
    push:
        branches: ['main', 'deploy']
    pull_request:
        branches: ['main', 'deploy']

jobs:
    ssh_connection:
        name: Connection on Virtual Machine
        runs-on: ubuntu-latest
        if: github.ref == 'refs/heads/main'
        needs:
            - build
        steps:
            - name: Checkout repo
              uses: actions/checkout@v3
            - name: Executing remote ssh commands to deploy
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.HOST }}
                  username: ${{ secrets.USER }}
                  key: ${{ secrets.SSH_KEY }}
                  port: 22
                  script: |
                      cd ${{ secrets.DIRECTORY_ROOT }}
                      bash scripts/docker-install.sh
    test:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [22.x]
        steps:
            - uses: actions/checkout@v4
            - name: Running Testings on Jest
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: 'npm'
                  cache-dependency-path: '**/package-lock.json'
            - run: npm ci
            - run: npm run test
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [22.x]
        needs:
            - test
        steps:
            - uses: actions/checkout@v4
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: 'npm'
                  cache-dependency-path: '**/package-lock.json'
            - run: npm ci
            - run: npm run build
